MODEL:
  META_ARCHITECTURE: "RetinaNet"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  RPN_ONLY: True
  BACKBONE:
    CONV_BODY: "R-101-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    FG_IOU_THRESHOLD: 0.5
    BG_IOU_THRESHOLD: 0.4
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 256
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.125, 0.0625, 0.03125)
    #POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  # Assume 4 gpus
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (360000, 480000)
  MAX_ITER: 540000
  IMS_PER_BATCH: 4
RETINANET:
  RETINANET_ON: True
  BACKBONE: "p3p7"
  SCALES_PER_OCTAVE: 3
  STRADDLE_THRESH: -1
  NUM_MASKS_TEST: 50
  BBOX_REG_BETA: 0.11
  SELFADJUST_SMOOTH_L1: True
